### ISSUE TITLE
Unusable "burn after reading" option

### ISSUE THREAD

**Issue by respawner** [moulecorp/pasthis#26]
# Summary

When trying to use the "burn after reading" option the paste becomes unavailable, using the latest version of this repo.

# Steps to reproduce

  1. Create a new paste
  2. Select "burn after reading"
  3. Send the paste
  4. Get redirected to see the paste

# Expected behavior

Create a new paste, get redirected to it but let it be available one more time. I think that the issue comes from step 4 described above.

**Comment by atenart** [comment]
Hey! Thanks for the bug report.

I just tested using your Pasthis instance, but was unable to reproduce the issue. I was redirected to the paste, but got one more chance to see it, as expected.

I know there could be issues with this feature when the paste URL is shared using chat clients pre-loading the page to get a preview. Is this your use-case?

**Comment by atenart** [comment]
Also, if you do click on the "raw" link, then it's impossible to share the URL.

**Comment by respawner** [comment]
Indeed, looks like you are right. Slack seems to cause the issue by trying to pre-load the page.

Sorry for the noise over here :(
